package ru.senla;

public enum ConfigurationType {

    DATASOURCE_GUEST,
    DATASOURCE_ROOM,
    DATASOURCE_ROOM_HISTORY,
    DATASOURCE_SERVICE,
    DATASOURCE_STAY_INFO,
    //-------------------
    REPOSITORY_GUEST,
    REPOSITORY_ROOM,
    REPOSITORY_ROOM_HISTORY,
    REPOSITORY_SERVICE,
    REPOSITORY_STAY_INFO,
    //--------------------
    SERVICE_GUEST,
    SERVICE_ROOM,
    SERVICE_SERVICES,
    SERVICE_STAY_INFO


}
